### ISSUE TITLE
centering text

### ISSUE THREAD

**Issue by eborbath** [kazuyanagimoto/quarto-slides-typst#2]
Hi!

I would also like to ask, how can I center text on the slide? I have tried something like: 

```
:::{style="text-align: center;"}
Centered text
:::
```

**Comment by kazuyanagimoto** [comment]
Unfortunately, [Typst CSS](https://quarto.org/docs/advanced/typst/typst-css.html) does not support the align environment. You cannot use `style=""` for the alignment.

However, my template allows the use of Typst functions as span and div classes. So, the following minimal example works.

```md
---
format:
  clean-typst:
    commands: [align]
    environments: [align]
---

# {}

## Center Aligned Text

[Span environment]{.align options="center"}

::: {.align options="center"}

Div environment

:::
```

This is because the lua filters convert `[TEXT]{.foo options="HOGE"}` to a Typst code `#foo(HOGE)[TEXT]`. Hence, all you need to do is register Typst functions to `commands`(for span)  and `environments` (for div) arguments in YAML.
